# This is a basic workflow to help you get started with Actions

name: run_changes

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
   inputs:
     tag:
       description: 'Enter tag for rollback'
       required: true
       
env:
    LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}
    LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_COMMAND_URL }}
    LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_COMMAND_USERNAME }}
    LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_COMMAND_PASSWORD }}
    LIQUIBASE_COMMAND_CHANGELOG_FILE: ${{ secrets.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
    LIQUIBASE_COMMAND_TAG: ${{ github.event.inputs.tag }}
    LIQUIBASE_HUB_MODE: off
    
jobs:

  Build_Job:
    runs-on: ubuntu-latest
    environment: 
      name: DEV

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.LB_GH_TOKEN }}
    - name: Running Flow
      uses: docker://liquibase/liquibase
      with:
        args: flow --flow-file=liquibase.flowfile.yaml
      env:
        LB_ENVIRONMENT: DEV
    - name: Checkin snapshot
      run: |
          git config user.name github-actions
          git config user.email molivas@liquibase.com
          git add .
          git commit -m "New Snapshots"
          git push
    
    
  Test_Job:
    needs: Build_Job
    runs-on: ubuntu-latest
    environment: 
      name: TEST

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.LB_GH_TOKEN }}
    - name: Running Flow
      uses: docker://liquibase/liquibase
      with:
        args: flow --flow-file=liquibase.flowfile.yaml
      env:
        LB_ENVIRONMENT: TEST
    - name: Checkin snapshot
      run: |
          git pull
          git config user.name github-actions
          git config user.email molivas@liquibase.com
          git add .
          git commit -m "New Snapshots $LB_ENVIRONMENT"
          git push

  Deploy_Prod_Job:
    needs: Test_Job
    runs-on: ubuntu-latest
    environment: 
      name: PROD

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.LB_GH_TOKEN }}
    - name: Running Flow
      uses: docker://liquibase/liquibase
      with:
        args: flow --flow-file=liquibase.flowfileprod.yaml
      env:
        LB_ENVIRONMENT: PROD
    - name: Checkin snapshot
      run: |
          git pull
          git config user.name github-actions
          git config user.email molivas@liquibase.com
          git add .
          git commit -m "New Snapshots"
          git push
        
  
